#LOG.RDK.TEST=DEBUG
#This sets the logging level for the "RI.Stack.LOG.RDK.TEST" category to DEBUG, meaning all messages of level DEBUG and higher (INFO, WARN, ERROR, FATAL) will be logged.
#LOG.RDK.SAMPLE=INFO
#This sets the logging level for the "RI.Stack.LOG.RDK.SAMPLE" category to INFO, meaning all messages of level INFO and higher (WARN, ERROR, FATAL) will be logged.
LOG.RDK.DEFAULT=WARNING
LOG.RDK.SI=INFO
